### ISSUE TITLE
Add real numbers in Result.Vue

### ISSUE THREAD

**Issue by vikiorf** [linusromland-ITHS/Backendprogrammering-och-Databaser-Grupprojektet#172]
"Showing 15 out of 196 results" should not be static.

**Comment by linusromland** [comment]
maybe do this from backend and sending it in the get route. To do it with sequilize and mongoose and fulfill the course requirement

**Comment by svante-jonsson** [comment]
[sequelize.fn('COUNT',...](https://sequelize.org/docs/v6/core-concepts/model-querying-basics/)
